version: 2
updates:
  - package-ecosystem: github-actions
    directories: [/, /actions/*]
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
    groups:
      pre-commit:
        patterns: ['*']
